name: Test Packaged Releases

on:
  workflow_dispatch:

jobs:
  test-brew:
    name: Test Homebrew package
    runs-on: macos-latest

    steps:
      - name: Set up Homebrew
        shell: bash
        run: |
          # Install Homebrew
          brew update
          brew -v
          # Set up SchemaCrawler tap
          brew tap SchemaCrawler/homebrew-tap
          echo '$ brew info schemacrawler'
          brew info --formula schemacrawler

      - name: Install SchemaCrawler with Homebrew
        shell: bash
        run: |
          # Install SchemaCrawler
          brew install --formula schemacrawler

      - name: Smoke test command
        run: |
          # Check that SchemaCrawler is installed
          schemacrawler --version

  test-sdkman:
    name: Test SDKMAN candidate
    runs-on: ubuntu-slim

    env:
      SDKMAN_DIR: ${{ github.workspace }}/.sdkman

    steps:
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - name: Set up SDKMAN
        shell: bash
        run: |
          # Install SDKMAN
          echo "$SDKMAN_DIR"
          curl -s "https://get.sdkman.io?ci=true" | bash
          source "$SDKMAN_DIR/bin/sdkman-init.sh"
          sdk version
          # Check for current version of SchemaCrawler
          echo '$ sdk list schemacrawler'
          sdk list schemacrawler | cat

      - name: Install SchemaCrawler with SDKMAN
        shell: bash
        run: |
          # Install SchemaCrawler
          source "$SDKMAN_DIR/bin/sdkman-init.sh"
          sdk install schemacrawler

      - name: Smoke test command
        shell: bash
        run: |
          # Check that SchemaCrawler is installed
          source "$SDKMAN_DIR/bin/sdkman-init.sh"
          schemacrawler.sh --version

  test-scoop:
    name: Test Scoop package
    runs-on: windows-latest

    steps:
      - name: Set up Scoop
        shell: pwsh
        run: |
          # Install Scoop
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          scoop --version
          scoop update
          # Check for current version of SchemaCrawler
          Write-Output '> scoop info schemacrawler'
          scoop info schemacrawler

      - name: Install SchemaCrawler with Scoop
        shell: pwsh
        run: |
          # Install SchemaCrawler
          $env:PATH += ";$env:USERPROFILE\scoop\shims"
          scoop install schemacrawler

      - name: Smoke test command
        shell: pwsh
        run: |
          # Check that SchemaCrawler is installed
          $env:PATH += ";$env:USERPROFILE\scoop\shims"
          schemacrawler --version

  test-winget:
    name: Test Winget package
    runs-on: windows-latest

    steps:
      - name: Set up Winget
        shell: pwsh
        run: |
          # Check Winget version
          winget --version
          # Check for current version of SchemaCrawler
          Write-Output '> winget show SchemaCrawler.SchemaCrawler'
          winget show SchemaCrawler.SchemaCrawler --accept-source-agreements

      - name: Install SchemaCrawler with Winget
        shell: pwsh
        run: |
          # Install SchemaCrawler
          winget install SchemaCrawler.SchemaCrawler --accept-package-agreements --accept-source-agreements

      - name: Smoke test command
        shell: pwsh
        run: |
          # Check that SchemaCrawler is installed
          schemacrawler.cmd --version

  test-chocolatey:
    name: Test Chocolatey package
    runs-on: windows-latest

    steps:
      - name: Set up Chocolatey
        shell: pwsh
        run: |
          # Check Chocolatey version
          choco --version
          # Check for current version of SchemaCrawler
          Write-Output '$ choco info schemacrawler'
          choco info schemacrawler

      - name: Install SchemaCrawler with Chocolatey
        shell: pwsh
        run: |
          # Install SchemaCrawler
          choco install schemacrawler -y

      - name: Smoke test command
        shell: pwsh
        run: |
          # Check that SchemaCrawler is installed
          schemacrawler --version
